import { useEffect, useState } from 'react';
import { Sparkles, Loader2, Clock } from 'lucide-react';
import { aiAPI } from '../api/client';

export default function AICoach() {
  const [coach, setCoach] = useState(null); const [roadmap, setRoadmap] = useState(null); const [weeks, setWeeks] = useState(4); const [loading, setLoading] = useState(''); const [error, setError] = useState('');
  useEffect(() => { aiAPI.getRoadmap().then(setRoadmap).catch(() => {}); }, []);
  const run = async (type) => { setLoading(type); setError(''); try { if (type === 'coach') setCoach(await aiAPI.getCoach()); else setRoadmap(await aiAPI.generateRoadmap(weeks)); } catch (err) { setError(err.response?.data?.message || 'AI generation failed.'); } finally { setLoading(''); } };
  const toggleTask = async (task) => { const updated = await aiAPI.updateRoadmapTask(task._id, !task.completed); setRoadmap(updated); };
  return <div className="max-w-5xl mx-auto p-4 sm:p-6 lg:p-8"><div className="mb-8"><div className="flex items-center gap-2 text-purple-600"><Sparkles className="w-5 h-5" /><span className="text-sm font-semibold">Gemini AI Coach</span></div><h1 className="mt-2 text-3xl font-bold text-slate-900 dark:text-white">Your next best placement steps</h1><p className="mt-2 text-slate-500">Plans use your profile, DSA progress, platform stats, resume analysis, and target companies.</p></div>{error && <p className="mb-5 p-3 bg-red-50 text-red-700 rounded-lg">{error}</p>}<div className="grid md:grid-cols-2 gap-6"><section className="bg-white dark:bg-[#131c31] border border-slate-200 dark:border-slate-700 rounded-2xl p-6"><h2 className="font-semibold text-slate-900 dark:text-white">Ask the coach</h2><button onClick={() => run('coach')} disabled={Boolean(loading)} className="mt-5 px-4 py-2 bg-purple-600 text-white rounded-lg disabled:opacity-60">{loading === 'coach' ? 'Thinking…' : 'Get my next actions'}</button>{coach && <div className="mt-4 space-y-3">{coach.actions?.map((action) => <div key={action.title} className="p-3 bg-slate-50 dark:bg-slate-800 rounded-xl"><p className="font-medium text-slate-900 dark:text-white">{action.title}</p><p className="text-sm text-slate-500">{action.reason}</p></div>)}</div>}</section><section className="bg-white dark:bg-[#131c31] border border-slate-200 dark:border-slate-700 rounded-2xl p-6"><h2 className="font-semibold text-slate-900 dark:text-white">Generate roadmap</h2><div className="mt-5 flex gap-3"><select value={weeks} onChange={(e) => setWeeks(Number(e.target.value))} className="px-3 py-2 rounded-lg border dark:bg-slate-800 dark:border-slate-600"><option value={2}>2 weeks</option><option value={4}>4 weeks</option><option value={8}>8 weeks</option><option value={12}>12 weeks</option></select><button onClick={() => run('roadmap')} disabled={Boolean(loading)} className="px-4 py-2 bg-blue-600 text-white rounded-lg disabled:opacity-60">{loading === 'roadmap' ? 'Building…' : 'Create roadmap'}</button></div></section></div>{roadmap && <section className="mt-6 bg-white dark:bg-[#131c31] border border-slate-200 dark:border-slate-700 rounded-2xl p-6"><h2 className="font-semibold text-slate-900 dark:text-white">Your editable roadmap</h2><p className="mt-2 text-slate-500">{roadmap.overview}</p><div className="mt-5 grid md:grid-cols-2 gap-4">{roadmap.weeks?.map((week) => <div key={week.week} className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800"><p className="font-semibold text-blue-600">Week {week.week}: {week.focus}</p>{week.tasks?.map((task) => <label key={task._id} className="mt-3 flex gap-2 text-sm text-slate-700 dark:text-slate-300"><input type="checkbox" checked={task.completed} onChange={() => toggleTask(task)} /> <span className={task.completed ? 'line-through text-slate-400' : ''}>{task.title}</span></label>)}</div>)}</div></section>}</div>;
}
