import { useEffect, useState } from 'react';
import { Sparkles } from 'lucide-react';
import { aiAPI } from '../api/client';
export default function PersonalizedSheet() {
  const [sheet, setSheet] = useState(null); const [style, setStyle] = useState('interview'); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  useEffect(() => { aiAPI.getSheet().then(setSheet).catch(() => {}); }, []);
  const generate = async () => { setLoading(true); setError(''); try { setSheet(await aiAPI.generateSheet(style)); } catch (e) { setError(e.response?.data?.message || 'Could not generate sheet.'); } finally { setLoading(false); } };
  const toggle = async (item) => { const updated = await aiAPI.updateSheetItem(item._id, !item.completed); setSheet(updated); };
  return <div className="max-w-5xl mx-auto p-4 sm:p-6 lg:p-8"><div className="flex items-center gap-2 text-purple-600"><Sparkles className="w-5 h-5"/><span className="font-semibold text-sm">Personalized preparation</span></div><h1 className="mt-2 text-3xl font-bold text-slate-900 dark:text-white">Your AI preparation sheet</h1><p className="mt-2 text-slate-500">An original plan based on your own CareerPilot progress—not copied third-party content.</p><div className="mt-6 flex gap-3"><select value={style} onChange={(e) => setStyle(e.target.value)} className="px-3 py-2 rounded-lg border dark:bg-slate-800 dark:border-slate-600"><option value="foundation">Foundation</option><option value="interview">Interview</option><option value="company">Company focused</option></select><button onClick={generate} disabled={loading} className="px-4 py-2 bg-purple-600 text-white rounded-lg disabled:opacity-60">{loading ? 'Generating…' : 'Generate my sheet'}</button></div>{error && <p className="mt-3 text-red-600">{error}</p>}{sheet && <section className="mt-6 bg-white dark:bg-[#131c31] border border-slate-200 dark:border-slate-700 rounded-2xl p-6"><h2 className="font-semibold text-slate-900 dark:text-white">{sheet.title}</h2><p className="mt-2 text-sm text-slate-500">{sheet.rationale}</p><div className="mt-5 space-y-3">{sheet.items?.map((item) => <label key={item._id} className="flex gap-3 p-4 bg-slate-50 dark:bg-slate-800 rounded-xl"><input type="checkbox" checked={item.completed} onChange={() => toggle(item)} className="mt-1"/><div><p className={item.completed ? 'line-through text-slate-400' : 'font-medium text-slate-900 dark:text-white'}>Day {item.days}: {item.topic}</p><p className="text-sm text-slate-500">{item.objective} · {item.difficulty}</p></div></label>)}</div></section>}</div>;
}
