import { useState } from 'react';
import { Loader2, Sparkles, CheckCircle2, Upload } from 'lucide-react';
import { aiAPI } from '../api/client';

export default function Resume() {
  const [extractedText, setExtractedText] = useState('');
  const [fileName, setFileName] = useState('');
  const [analysis, setAnalysis] = useState(null);
  const [uploading, setUploading] = useState(false);
  const [analyzing, setAnalyzing] = useState(false);
  const [error, setError] = useState('');
  const upload = async (event) => { const file = event.target.files?.[0]; if (!file) return; setUploading(true); setError(''); try { const result = await aiAPI.uploadResume(file); setExtractedText(result.resumeText); setFileName(result.fileName); setAnalysis(null); } catch (err) { setError(err.response?.data?.message || 'Could not extract this resume.'); } finally { setUploading(false); event.target.value = ''; } };
  const analyze = async () => { setAnalyzing(true); setError(''); try { const result = await aiAPI.analyzeResume(extractedText); setAnalysis(result.analysis); setExtractedText(''); } catch (err) { setError(err.response?.data?.message || 'Unable to analyze the resume.'); } finally { setAnalyzing(false); } };
  return <div className="max-w-5xl mx-auto p-4 sm:p-6 lg:p-8"><div className="mb-8"><div className="flex items-center gap-2 text-blue-600"><Sparkles className="w-5 h-5"/><span className="text-sm font-semibold">AI Resume Analyzer</span></div><h1 className="mt-2 text-3xl font-bold text-slate-900 dark:text-white">Turn your resume into a placement plan</h1><p className="mt-2 text-slate-500">Your resume is extracted in memory and never displayed as text.</p></div><div className="bg-white dark:bg-[#131c31] border border-slate-200 dark:border-slate-700 rounded-2xl p-6"><label className="cursor-pointer inline-flex items-center gap-2 px-4 py-2.5 bg-blue-600 text-white rounded-lg hover:bg-blue-700"><Upload className="w-4 h-4"/>{uploading ? 'Extracting...' : 'Upload Resume'}<input type="file" className="hidden" accept=".pdf,.docx,.txt" onChange={upload}/></label>{fileName && !analyzing && <p className="mt-4 text-sm text-green-600">{fileName} uploaded successfully ✓</p>}{error && <p className="mt-3 text-sm text-red-600">{error}</p>}{extractedText && <button onClick={analyze} disabled={analyzing} className="mt-4 ml-3 inline-flex items-center gap-2 px-5 py-2.5 bg-purple-600 text-white rounded-lg disabled:opacity-60">{analyzing ? <Loader2 className="w-4 h-4 animate-spin"/> : <Sparkles className="w-4 h-4"/>}{analyzing ? 'Analyzing your resume...' : 'Analyze Resume'}</button>}{analyzing && <p className="mt-3 text-sm text-slate-500">Analyzing your resume...</p>}</div>{analysis && <Analysis analysis={analysis}/>}</div>;
}
function Analysis({ analysis }) { return <div className="mt-6 grid lg:grid-cols-3 gap-5"><section className="lg:col-span-2 bg-white dark:bg-[#131c31] border border-slate-200 dark:border-slate-700 rounded-2xl p-6"><div className="flex justify-between"><h2 className="font-semibold text-slate-900 dark:text-white">Resume Analysis</h2><span className="text-xl font-bold text-blue-600">ATS {analysis.atsScore}/100</span></div><p className="mt-3 text-slate-600 dark:text-slate-300">{analysis.summary}</p><h3 className="mt-6 font-semibold text-slate-900 dark:text-white">Skills extracted</h3><div className="mt-3 flex flex-wrap gap-2">{analysis.skills?.map((skill) => <span key={skill} className="px-2.5 py-1 bg-blue-50 text-blue-700 rounded-full text-sm">{skill}</span>)}</div></section><section className="space-y-5"><Card title="Strengths" items={analysis.strengths} good/><Card title="Weaknesses / Missing keywords" items={analysis.gaps}/><Card title="Suggestions" items={analysis.suggestions}/></section></div>; }
function Card({ title, items, good }) { return <div className="bg-white dark:bg-[#131c31] border border-slate-200 dark:border-slate-700 rounded-2xl p-5"><h2 className="font-semibold text-slate-900 dark:text-white">{title}</h2><ul className="mt-3 space-y-2 text-sm text-slate-600 dark:text-slate-300">{items?.map((item) => <li key={item} className="flex gap-2"><CheckCircle2 className={`w-4 h-4 mt-0.5 shrink-0 ${good ? 'text-green-500' : 'text-amber-500'}`}/>{item}</li>)}</ul></div>; }
